/**
 * This file was automatically generated by Dyrected CLI.
 * DO NOT MODIFY IT BY HAND.
 */

export interface Media {
  id: string;
  filename: string;
  filesize: number;
  mimeType: string;
  url: string;
  width?: number;
  height?: number;
  focalPoint?: { x: number; y: number };
  blurhash?: string;
  sizes?: Record<
    string,
    { filename?: string; url?: string; width?: number; height?: number }
  >;
  createdAt: string;
  updatedAt: string;
  alt: string;
  caption?: string;
}

// URL field types
export type UrlFieldValue =
  | {
      type: "custom";
      url: string;
      label?: string;
    }
  | {
      type: "internal";
      url: string;
      relationTo: string;
      value: string;
      label?: string;
    };

// Backward compatibility for simple string URLs
export type UrlField = UrlFieldValue | string;

export interface Admins {
  id: string;
  name?: string;
  email: string;
  roles?: string[];
  createdAt: string;
  updatedAt: string;
}

export interface Wishlist_items {
  id: string;
  image?: Media | string;
  name: string;
  description?: string;
  category?: "kitchen" | "travel" | "home" | "cash-fund" | "other";
  price: number;
  fundingType?: "fixed" | "crowdfund";
  maxQuantity: number;
  link?: UrlField;
  isHidden?: boolean;
  amountRaised?: number;
  contributorCount?: number;
  reservedCount?: number;
  createdAt: string;
  updatedAt: string;
}

export interface Reservations {
  id: string;
  item: Wishlist_items | string;
  guestName: string;
  guestEmail?: string;
  guestPhone?: string;
  contributionAmount?: number;
  reservedAt?: string;
  message?: string;
  createdAt: string;
  updatedAt: string;
}

export interface Rsvp_groups {
  id: string;
  rsvpLink?: string;
  name: string;
  slug?: string;
  maxCapacity: number;
  isActive?: boolean;
  confirmedCount?: number;
  declinedCount?: number;
  description?: string;
  createdAt: string;
  updatedAt: string;
}

export interface Rsvp_records {
  id: string;
  rsvpEditLink?: string;
  leadName: string;
  leadEmail: string;
  leadPhone: string;
  hasSpouse?: boolean;
  spouseName?: string;
  attending: boolean;
  group: Rsvp_groups | string;
  selectedEvents?: Array<Events | string>;
  wantsAsoebi?: boolean;
  asoebiYards?: "2" | "3" | "4" | "5" | "6";
  asoebiReminder?: Record<string, unknown>;
  message?: string;
  submittedAt?: string;
  editToken?: string;
  accessCardPreview?: Record<string, unknown>;
  invitationSent?: boolean;
  invitationSentAt?: string;
  invitationSentVia?: "whatsapp" | "email";
  checkedIn?: boolean;
  checkIn?: Check_ins | string;
  createdAt: string;
  updatedAt: string;
}

export interface Events {
  id: string;
  order?: number;
  name: string;
  date: string;
  venueName: string;
  venueAddress: string;
  dressCode?: string;
  photo?: Media | string;
  collectsRsvp?: boolean;
  createdAt: string;
  updatedAt: string;
}

export interface Check_ins {
  id: string;
  checkInScanner?: Record<string, unknown>;
  rsvpRecord: Rsvp_records | string;
  event?: Events | string;
  guestName?: string;
  partySize?: number;
  scannedBy?: string;
  notes?: string;
  createdAt: string;
  updatedAt: string;
}

export interface Site_settingsGlobal {
  partnerOneName: string;
  partnerTwoName: string;
  weddingDate: string;
  weddingDateText?: string;
  weddingLocation?: string;
  hashtag?: string;
  heroImage?: Media | string;
  heroSubtitle?: string;
  countdownPhotos?: Array<Media | string>;
  wishlistTeaserImage?: Media | string;
  wishlistTeaserTitle?: string;
  wishlistTeaserDescription?: string;
  rsvpTeaserImage?: Media | string;
  footerImage?: Media | string;
  storyFormat?: "timeline";
  storySubtitle?: string;
  storyTitle?: string;
  storyDescription?: string;
  storyPhotos?: Array<{
    label: string;
    title: string;
    description: string;
    photo?: Media | string;
  }>;
  faqs?: Array<{
    question: string;
    answer: string;
  }>;
  rsvpCutoffDate: string;
  rsvpCutoffTime?: string;
  bankName?: string;
  accountNumber?: string;
  accountName?: string;
}

export interface Asoebi_settingsGlobal {
  bankName: string;
  accountNumber: string;
  accountName: string;
  whatsAppContact: string;
}

export interface DyrectedSchema {
  collections: {
    admins: Admins;
    media: Media;
    wishlist_items: Wishlist_items;
    reservations: Reservations;
    rsvp_groups: Rsvp_groups;
    rsvp_records: Rsvp_records;
    events: Events;
    check_ins: Check_ins;
  };
  globals: {
    site_settings: Site_settingsGlobal;
    asoebi_settings: Asoebi_settingsGlobal;
  };
}

declare module "@dyrected/sdk" {
  interface Register {
    schema: DyrectedSchema;
  }
}
